services:
  database:
    image: 'mysql:latest'
    restart: unless-stopped
    env_file: '.env'
    environment:
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_ALLOW_EMPTY_PASSWORD: '${MYSQL_ALLOW_EMPTY_PASSWORD}'
    ports:
      - '${MYSQL_PORT}'

  static-site:
    image: dockersamples/static-site
    build: .
    ports:
      - "80:80"
    restart: always

  ngrok:
    image: ngrok/ngrok:latest
    command:
      - "http"
      - "80"
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
      NGROK_DOMAIN: "guinea-pet-freely.ngrok-free.app"
    ports:
      - "4040:4040"
