# App
server:
  servlet:
    application-display-name: metakyasshu
    context-path: /metakyasshu
    multipart:
      max-file-size: 16MB
      max-request-size: 16MB

# Jackson
spring:
  jackson:
    default-property-inclusion: non_null

  # Datasource
  datasource:
    url: jdbc:mysql://localhost:3306/db_metakyasshu
    username: 'senzalla'
    password: '@braTe07'
#    username: '${MYSQL_USER}'
#    password: '${MYSQL_PASSWORD}'
    driver-class-name: com.mysql.cj.jdbc.Driver



  # JPA
  jpa:
    hibernate:
#      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  # Email
  mail:
    port: 587
    protocol: smtp
    host: sandbox.smtp.mailtrap.io
    username: '171772bf7d7b12'
    password: 'f94218bfab5679'

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


# SWAGGER
springdoc:
  swagger-ui:
    path: '/'

swagger:
  enable: true

scheduled:
  enable: false

# JWT
jwt:
  api:
    expiration: 86400000
    secret: a4c47614bbbb0af8a0d4906f9508a45a61d854282e2b382900b29187cc448545


host:
  base_url: http://localhost:4200
  confirmation_url: '${host.base_url}/confirm?token='
  reset_password_url: '${host.base_url}/reset-password?token='
  confirmation_invite_url: '${host.base_url}/invitation/confirm-invite?token='

# LOGGING
logging:
  level:
    root: info
    web: info
    dev:
      senzalla: DEBUG

